### ISSUE TITLE
Nodered error when trying to connect to loxone miniserver

### ISSUE THREAD

**Issue by cocos-cz** [alladdin/node-lox-ws-api#24]
originaly posted on node-red-contrib-loxone  -  https://github.com/codmpm/node-red-contrib-loxone/issues/58 and suggested that error comes from this node:

I am trying to get up and running node-red with my loxone miniserver, but the moment I set the miniserver details, nodered starts crashing..

I am getting this error:
TypeError: Cannot read property 'closeDescription' of undefined
at Connection. (/home/pi/.node-red/node_modules/node-lox-ws-api/lib/Connection.js:64:62)
at WebSocketClient.emit (events.js:314:20)
at ClientRequest.handleRequestError (/home/pi/.node-red/node_modules/websocket/lib/WebSocketClient.js:227:14)
at ClientRequest.emit (events.js:314:20)
at Socket.socketErrorListener (_http_client.js:427:9)
at Socket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.

Thats when I try to setup "online" node to test the connection.. When I delete everything from the flow, i am getting:
WebSocket error: Socket Error: undefined ERR_STREAM_WRITE_AFTER_END 1006

and after some time crash again... seems like I am not able to connect to the miniserver.. anybody out there, who could help, how to make stable login into miniserver?

R4pi 8GB, on raspberry Pi OS, all updates done.

Thanks

**Comment by rc-itcon** [comment]
Hello.
Same issue with latest homebridge und Loxone Version. 

using Loxone-Homebridge Plugin 

Thank you

**Comment by killeriq** [comment]
same here :( didnt changed any Loxone version...just password, before was running fine
