### ISSUE TITLE
Cannot read property 'sendUTF' of undefined

### ISSUE THREAD

**Issue by Sroose** [alladdin/node-lox-ws-api#5]
Hello,

The library sometimes crashes, I assume when the connection is dropped:

    /usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/Connection.js:80

        that._ws.connection.sendUTF('keepalive');

                           ^
    TypeError: Cannot read property 'sendUTF' of undefined

    at null._repeat (/usr/local/lib/node_modules/homebridge-loxone-ws/node_modules/node-lox-ws-api/lib/Connection.js:80:28)

    at wrapper [as _onTimeout] (timers.js:275:11)

    at Timer.listOnTimeout (timers.js:92:15)

thanks for having a look!

**Comment by alladdin** [comment]
Fixed in version 0.2.5
