### ISSUE TITLE
Cannot read property 'sendUTF' of undefined : Line 109 : in Version 0.2.5

### ISSUE THREAD

**Issue by arnega** [alladdin/node-lox-ws-api#6]
Hello,

everytime when the Loxone does a Restart, the following appears:

[2017-02-07 15:40:52] [Loxone] LOXONE WS: connect
[2017-02-07 15:40:52] [Loxone] LOXONE WS: connect
/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:109
    this._ws.connection.sendUTF(message);
                       ^

TypeError: Cannot read property 'sendUTF' of undefined
    at Connection.send (/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:109:24)
    at Object.callback (/usr/lib/node_modules/node-lox-ws-api/lib/Auth/Hash.js:32:34)
    at /usr/lib/node_modules/node-lox-ws-api/lib/API.js:180:18
    at Array.some (native)
    at API._message_text (/usr/lib/node_modules/node-lox-ws-api/lib/API.js:178:25)
    at .<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/API.js:104:14)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Connection.handle_message (/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:134:18)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:103:14)

**Comment by alladdin** [comment]
New version 0.2.6 could fix this issue
