### ISSUE TITLE
TypeError: Cannot read property 'authorize' of undefined - Version 0.2.6

### ISSUE THREAD

**Issue by arnega** [alladdin/node-lox-ws-api#7]
Hello,

a new bug in Version 0.2.6... When the Miniserver does a reboot, the Script the reconnect, but after a few times i got this error:

[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:24] [Loxone] LOXONE WS: connect
/usr/lib/node_modules/node-lox-ws-api/lib/API.js:80
        that._auth.authorize();
                  ^

TypeError: Cannot read property 'authorize' of undefined
    at .<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/API.js:80:19)
    at emitNone (events.js:86:13)
    at emit (events.js:185:7)
    at WebSocketClient.<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:67:14)
    at emitOne (events.js:96:13)
    at WebSocketClient.emit (events.js:188:7)
    at WebSocketClient.succeedHandshake (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:335:10)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:319:10)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:248:14)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)

Here the full log:

[2017-02-14 15:22:30] [Loxone] [switch] iOS - send message to Außenbeleuchtung Haus hinten: On
[2017-02-14 15:22:32] [Loxone] [switch] iOS - send message to Außenbeleuchtung Haus hinten: Off
[2017-02-14 15:22:45] [Loxone] LOXONE WS: keepalive 1
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:13] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:15] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:15] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:15] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:15] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:15] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:15] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:16] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:17] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:17] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:17] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:17] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:17] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:18] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:19] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:19] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:19] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:19] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:20] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Eingang VI3: Off
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Licht: Off
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Reset Hzg KiZi Ost: Off
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Licht komplett aus: Off
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Rolläden komplett auf: Off
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Rolläden komplett zu: Off
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:21] [Loxone] [switch] iOS - send message to Miniserver Reboot: Off
[2017-02-14 15:23:21] [Loxone] LOXONE WS: connect
[2017-02-14 15:23:24] [Loxone] LOXONE WS: connect
/usr/lib/node_modules/node-lox-ws-api/lib/API.js:80
        that._auth.authorize();
                  ^

TypeError: Cannot read property 'authorize' of undefined
    at .<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/API.js:80:19)
    at emitNone (events.js:86:13)
    at emit (events.js:185:7)
    at WebSocketClient.<anonymous> (/usr/lib/node_modules/node-lox-ws-api/lib/Connection.js:67:14)
    at emitOne (events.js:96:13)
    at WebSocketClient.emit (events.js:188:7)
    at WebSocketClient.succeedHandshake (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:335:10)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:319:10)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/node-lox-ws-api/node_modules/websocket/lib/WebSocketClient.js:248:14)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)

**Comment by alladdin** [comment]
Ok, it's error in authorization phase. But there are so many connects in small amount of time. Do you have problems with connection to miniserver?

**Comment by arnega** [comment]
Not realy, but i have a lot of components, from wich the script will ask the status i think. Could it be? 

I have generate a full log since startup:

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[2017-02-14 16:23:54] Loaded plugin: homebridge-blinds
[2017-02-14 16:23:54] Registering accessory 'homebridge-blinds.BlindsHTTP'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-http
[2017-02-14 16:23:54] Registering accessory 'homebridge-http.Http'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-loxone
[2017-02-14 16:23:54] Registering platform 'homebridge-loxone.Loxone'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-loxone-garage
[2017-02-14 16:23:54] Registering accessory 'homebridge-loxone-garage.loxone-garage'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-loxone-light-switch
[2017-02-14 16:23:54] Registering accessory 'homebridge-loxone-light-switch.loxone-light-switch'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-loxone-rollo
[2017-02-14 16:23:54] Registering accessory 'homebridge-loxone-rollo.loxone-rollo'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:54] Loaded plugin: homebridge-loxone-shutters
[2017-02-14 16:23:54] Registering accessory 'homebridge-loxone-shutters.loxone-shutters'
[2017-02-14 16:23:54] ---
[2017-02-14 16:23:55] Loaded plugin: homebridge-loxone-temperature
[2017-02-14 16:23:55] Registering accessory 'homebridge-loxone-temperature.loxone-temperature'
[2017-02-14 16:23:55] ---
[2017-02-14 16:23:55] Loaded plugin: homebridge-loxone-ws
homebridge API version: 2.1
[2017-02-14 16:23:55] Registering platform 'homebridge-loxoneWs.LoxoneWs'
[2017-02-14 16:23:55] ---
[2017-02-14 16:23:55] Loaded config.json with 0 accessories and 1 platforms.
[2017-02-14 16:23:55] ---
[2017-02-14 16:23:55] Loading 1 platforms...
[2017-02-14 16:23:55] [Loxone] Initializing LoxoneWs platform...
[2017-02-14 16:23:55] [Loxone] LoxPlatform Init
SETTING UP WS LISTENER
New WS: 192.168.29.27:80
[2017-02-14 16:23:55] [Loxone] Getting Loxone configuration.
[2017-02-14 16:23:55] [Loxone] Platform - Connecting to http://homebridge:homebridge@192.168.29.27:80/data/LoxApp3.json
[2017-02-14 16:23:55] [Loxone] LOXONE WS: connect
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Außenbeleuchtung Haus hinten
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Bewegungsmelder SW
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Eingangslicht
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Hausnummer
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Eingangslicht Morgens autom. einschalten' of type Daytimer is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Regen' of type Presence is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Automatikjalousie_Bad_EG
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Bad OG Motion Sensor Air Lichtsensor' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Bad OG OL
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Bad OG Spiegel
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Präsenz Bad OG' of type Presence is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Helligkeit Bad OG Licht' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Automatikjalousie_Büro
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatursensor Dachgeschoss
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatur_Nord
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'E-Verteiler OG Temperatursensor' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Esszimmer_OL
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Deckenlicht_Flur_EG
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Stehlampe_Flur_EG
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Zeitschaltuhr1 Eingang I1' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Eingang VI3
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Haustür' of type Intercom is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Licht
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Klingel TK
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Türklingel
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Onlinestatus Flurlampe' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Flur_OG_OL
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Außentemperatusabfrage
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ Ost Lichtsensor' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: KiZi Ost OL
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: KiZi Ost ST
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Präsenz' of type Presence is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Automatikjalousie_KZ_Ost
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Inteligente Raumregelung KZ Ost' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Intelligente Raumregelung' of type IRoomController is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Heating' of type IRCDaytimer is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Cooling' of type IRCDaytimer is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ Ost Hzg Eingang I1' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ Ost Hzg Stellantrieb' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Reset Hzg KiZi Ost
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ West Lichtsensor' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: KiZi West OL
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: KiZi West ST
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Deckenleuchte_SZ
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Automatikjalousie_SZ
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'SZ Schalter EG Luftfeuchtigkeitssensor' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatur SZ EG
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'SZ Schalter EG Batterie Kapazität' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Terrassenbeleuchtung
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatur kalter Keller
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Kühlschrank Medion' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Tiefkühler' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Eckleuchte_Wohnzimmer
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Weihnachtsbaum
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Automatikjalousie_WZ
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'HZ_WZ_BatterieState' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'HZ_WZ_LowBatterie' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'HZ_WZ_VentilState' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Anwesenheitssimulation' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Kindersicherung
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Urlaub
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Anw.Simulation Zufall Licht aus' of type Daytimer is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Licht komplett aus
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Aktivierung AUT Beschattung' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Rolläden komplett auf
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Rolläden komplett zu
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Morgens Rollo zentral auf' of type Daytimer is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperaturvergleich AUT Beschattung
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Dämmerung zentrale Beleuchtung' of type UpDownAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Dämmerung zentrale Beschattung' of type UpDownAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ Ost Hzg Ventil steckt fest' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Helligkeit' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Helligkeit Dach' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Luftgüte' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Regensensor' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Strahlung AKTIV' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Strahlung Dach' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Strahlung Vergl.' of type UpDownAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatur Vergl.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatur_Dach
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Temperatursensor Außen
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'rel. Luftfeuchte' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'KZ Ost Batterie Kapazität' of type InfoOnlyAnalog is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Offset EG' of type Slider is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Offset Gesamtverbrauch' of type Slider is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Offset KG' of type Slider is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Offset OG' of type Slider is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Verbrauch Reset
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Verbrauchszähler' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Verbrauchszähler EG' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Verbrauchszähler KG' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Verbrauchszähler OG' of type Meter is an item not handled.
[2017-02-14 16:23:55] [Loxone] Platform - Accessory Found: Miniserver Reboot
[2017-02-14 16:23:55] [Loxone] Platform - The widget 'Onlinestatus Loxone Air Base Extension OG' of type InfoOnlyDigital is an item not handled.
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Außenbeleuchtung Haus hinten'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Bewegungsmelder SW'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Eingangslicht'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Hausnummer'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Automatikjalousie_Bad_EG'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Bad OG OL'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Bad OG Spiegel'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Automatikjalousie_Büro'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatursensor Dachgeschoss'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatur_Nord'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Esszimmer_OL'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Deckenlicht_Flur_EG'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Stehlampe_Flur_EG'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Eingang VI3'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Licht'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Klingel TK'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Türklingel'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Flur_OG_OL'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Außentemperatusabfrage'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'KiZi Ost OL'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'KiZi Ost ST'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Automatikjalousie_KZ_Ost'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Reset Hzg KiZi Ost'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'KiZi West OL'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'KiZi West ST'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Deckenleuchte_SZ'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Automatikjalousie_SZ'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatur SZ EG'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Terrassenbeleuchtung'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatur kalter Keller'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Eckleuchte_Wohnzimmer'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Weihnachtsbaum'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Automatikjalousie_WZ'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Kindersicherung'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Urlaub'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Licht komplett aus'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Rolläden komplett auf'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Rolläden komplett zu'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperaturvergleich AUT Beschattung'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatur Vergl.'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatur_Dach'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Temperatursensor Außen'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Verbrauch Reset'...
[2017-02-14 16:23:55] [Loxone] Initializing platform accessory 'Miniserver Reboot'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2017-02-14 16:23:55] Homebridge is running on port 51826.

**Comment by arnega** [comment]
Sorry - i closed it...
